root: "D:/projects"
anchors:
  project: ".ign_project"
  phase: ".ign_phase"
  directory: ".ign_dir"
  build: ".ign_build"
  sequence: ".ign_sequence"
  shot: ".ign_shot"
  task: ".ign_task"
  asset: ".ign_asset"
  assetversion: ".ign_assetversion"