#!/bin/bash

if ! command -v gnome-terminal &> /dev/null; then
    gnome-terminal \
        --tab --title="server" -e "bash -c 'cd backend && ./src/bin/linux/start_server'" \
        --tab --title="client" -e "bash -c 'cd backend && ./src/bin/linux/start_client'" \
        --tab --title="node" -e "bash -c 'cd ../frontend && npm start'" \
        --tab --title="electron" -e "bash -c 'npm run electron'"
elif ! command -v konsole &> /dev/null; then
    konsole --hold --new-tab -e $SHELL -c "cd backend && ./src/bin/linux/start_server" &
    konsole --hold --new-tab -e $SHELL -c "cd backend && ./src/bin/linux/start_client" &
    konsole --hold --new-tab -e $SHELL -c "cd ../frontend && npm start" &
    konsole --hold --new-tab -e $SHELL -c "cd ../frontend && npm run electron"
