#!/bin/bash

# if ! command -v gnome-terminal &> /dev/null; then
#     gnome-terminal \
#         --tab --title="server" -e "bash -c 'cd backend && ./src/bin/linux/start_server'" \
#         --tab --title="client" -e "bash -c 'cd backend && ./src/bin/linux/start_client'" \
#         --tab --title="node" -e "bash -c 'cd ../frontend && npm start'" \
#         --tab --title="electron" -e "bash -c 'npm run electron'"
# elif ! command -v konsole &> /dev/null; then
#     konsole --hold --new-tab -e $SHELL -c "cd backend && ./src/bin/linux/start_server" &
#     konsole --hold --new-tab -e $SHELL -c "cd backend && ./src/bin/linux/start_client" &
#     konsole --hold --new-tab -e $SHELL -c "cd ../frontend && npm start" &
#     konsole --hold --new-tab -e $SHELL -c "cd ../frontend && npm run electron"
# fi

cd $0/backend
/bin/sh -ec "./src/bin/linux/start_server"
/bin/sh -ec "./src/bin/linux/start_client"
cd $0/frontend
/bin/sh -ec "npm start"
/bin/sh -ec "npm run electron"
