name: Build/release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false  
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install backend requirements
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Tools cleanup
        run: python tools_cleanup.py

      - name: Build and copy backend
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MAC_CERT }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MAC_PW }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.MAC_CERT_NAME }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MAC_KEYCHAIN_CI_PW }}
        # working-directory: ./backend
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          
          security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain 
          security default-keychain -s build.keychain
          security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain
          cd ./backend
          python build_and_copy.py
      
      # - name: Codesign backend
      #   env: 
      #     MACOS_CERTIFICATE: ${{ secrets.MAC_CERT }}
      #     MACOS_CERTIFICATE_PWD: ${{ secrets.MAC_PW }}
      #     MACOS_CERTIFICATE_NAME: ${{ secrets.MAC_CERT_NAME }}
      #     MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MAC_KEYCHAIN_CI_PW }}
      #   run: |
      #     echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          
      #     security create-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain 
      #     security default-keychain -s build.keychain
      #     security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PWD" build.keychain
      #     security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
      #     security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PWD" build.keychain
          
      #     /usr/bin/codesign --force -s "$MACOS_CERTIFICATE_NAME" --options runtime target/mac/Espanso.app -v

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        env: 
          CI: false

      - name: Deploy
        working-directory: ./frontend
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CSC_LINK: ${{ runner.os == 'macOS' && secrets.MAC_CERT || secrets.WIN_CERT }}
          CSC_KEY_PASSWORD: ${{ runner.os == 'macOS' && secrets.MAC_PW || secrets.WIN_PW }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
